package rars.corrector;

import rars.concolic.ConcolicInterpreter;

import java.io.*;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

/**
 * Entry point of the automatic correction process for RARS assignments.
 */
public class Corrector {

    public static CorrectorOptions opt;

    /**
     * Executes a source file through ConcolicInterpreter, passing it the
     * file's path followed by the supplied arguments.
     *
     * @param filename  source file to execute
     */
    public static void concExecFile(File filename) {
        try {
            ConcolicInterpreter.runInterpreter(filename.getPath(), opt.getInterpreterOptions());
        } catch (Exception e) {
            System.err.println("Error while executing " + filename);
            e.printStackTrace();
        }
    }

    /**
     * Executes a student file, providing the content of the given input files
     * as the known user entries.
     *
     * @param studentFile student file to execute
     * @param knownInputs known inputs files (originating from the master file) to
     *                    supply as input for the execution
     */
    public static void execStudentFile(File studentFile, File[] knownInputs) {
        updateUserEntries(knownInputs);
        concExecFile(studentFile);
    }

    /**
     * Generates a stable set of reference inputs/outputs for every student file
     * by alternately running the master file and the student file.
     *
     * @param files files manager holding the master file and the student files
     *              to process
     */
    public static void generateTestFiles(FilesManager files) {
        concExecFile(files.MASTER_FILE);
        files.saveExecutionResults();

        for (File studentFile : files.getStudentFiles()) {

            boolean stableInputs = false;

            while (!stableInputs) {
                File[] knownInputs = files.getMasterInputsFiles();
                execStudentFile(studentFile, knownInputs);

                File[] studentInputs = files.getExecInputFiles();
                File[] newInputs = findNewInputs(studentInputs, knownInputs);

                if (newInputs.length == 0) {
                    stableInputs = true;
                } else {
                    updateMasterList(newInputs, files);
                }
            }
        }
    }

    /**
     * Determines which inputs generated by running a student file are not yet
     * part of the known inputs.
     *
     * @param studentInputs inputs (both known and new) generated by running the
     *                      student file
     * @param knownInputs   inputs already known, used as a reference
     * @return an array containing the new inputs, in the same order as
     *         studentInputs; an empty array if no new input was produced
     */
    public static File[] findNewInputs(File[] studentInputs, File[] knownInputs) {
        File[] newInputs;
        if (studentInputs.length - knownInputs.length > 0) {
            newInputs = new File[studentInputs.length - knownInputs.length];
        } else {
            newInputs = new File[0];
        }

        if (studentInputs.length > knownInputs.length) {
            int i = 0;
            int j = knownInputs.length;
            while (j < studentInputs.length) {
                newInputs[i] = studentInputs[j];
                ++i; ++j;
            }
        }
        return newInputs;
    }

    /**
     * Runs the master file on newly discovered inputs from a student file in
     * order to produce the corresponding reference outputs, then saves the
     * results obtained.
     *
     * @param newInputs new inputs to supply to the master file
     * @param files     file manager holding the master file
     */
    public static void updateMasterList(File[] newInputs, FilesManager files) {
        updateUserEntries(newInputs);
        concExecFile(files.MASTER_FILE);
        files.saveExecutionResults();
    }

    private static void updateUserEntries(File[] inputs) {
        if(inputs != null && inputs.length != 0) {
            int i = 0;
            String[] masterArgs = new String[inputs.length + 2];
            masterArgs[i++] = "--user-entries";
            masterArgs[i++] = "" + inputs.length;
            for (File f : inputs) {
                masterArgs[i++] = f.getPath();
            }

            opt.checkOption(masterArgs, 0);
        }
    }

    /**
     * Compares, input by input, the outputs produced by the most recently
     * executed student file against the master file's reference outputs, and
     * records the result in the correction file.
     *
     * @param files file manager providing access to the master and student
     *              inputs/outputs, as well as to the correction file
     */
    public static void compareOutputs(FilesManager files) {
        File[] masterInputs = files.getMasterInputsFiles();
        File[] studentInputs = files.getExecInputFiles();
        File[] masterOutputs = files.getMasterOutputsFiles();
        File[] studentOutputs = files.getExecOutputFiles();

        try {
            PrintWriter pw = new PrintWriter(new FileWriter(files.CORRECTION_FILE, true));
            boolean success = true;
            for (int i = 0; i < masterOutputs.length && i < studentOutputs.length; ++i) {
                String studentOutput = Files.readString(studentOutputs[i].toPath());
                String masterOutput = Files.readString(masterOutputs[i].toPath());

                if (!studentOutput.equals(masterOutput)) {
                    pw.println("FAIL");
                    pw.println(masterInputs[i].getName());
                    pw.println("Teacher Inputs : " + Files.readString(masterInputs[i].toPath()));
                    pw.println(studentInputs[i].getName());
                    pw.println("Student Inputs : " + Files.readString(studentInputs[i].toPath()));
                    pw.println(masterOutputs[i].getName());
                    pw.println("Teacher Outputs : " + Files.readString(masterOutputs[i].toPath()));
                    pw.println(studentOutputs[i].getName());
                    pw.println("Student Outputs : " + Files.readString(studentOutputs[i].toPath()));
                    success = false;
                }
            }

            if (success) {
                pw.println("SUCCESS");
            }
            pw.flush();
            pw.close();
        } catch (IOException e) {
            System.out.println("Error while reading output: " + e.getMessage());
        }
    }

    /**
     * Tests every student file known to the file manager: for each one
     * executes it on the master's reference inputs, then compares its
     * outputs against the master's via compareOutputs.
     *
     * @param files file manager holding the student files to test as well as
     *              the master's reference inputs
     */

    public static void testStudents(FilesManager files) {
        File[] knownInputs = files.getMasterInputsFiles();
        for (int i = 0; i < files.getNumberOfFiles(); ++i) {
            files.printStudentHeader(i);
            execStudentFile(files.getStudentFile(i), knownInputs);
            compareOutputs(files);
        }
    }

    /**
     * Entry point of the correction program.
     *
     * Expects at least two arguments: the path to the teacher file, followed by
     * the path of at least one student file.
     *
     * @param args command-line arguments:
     *             args[0]: the path of the teacher file
     *             args[1..n-1]: the paths of the students
     *             files to correct
     */
    public static void main(String[] args) {
        if (args.length < 2) {
            System.out.println("Invalid number of arguments");
            System.exit(1);
        }

        opt = new CorrectorOptions();

        String[] cleanArgs = opt.checkOptions(args);

        FilesManager files = new FilesManager(cleanArgs);

        updateMasterList(opt.getUserTests(), files);

        generateTestFiles(files);

        testStudents(files);
    }
}
