package rars.corrector;

import rars.concolic.ConcolicInterpreter;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Comparator;

/**
 * Manages all the files used by the automatic correction process: the master
 * file (the teacher's solution), the student files to be tested, and the
 * directories containing the inputs and outputs generated by
 * ConcolicInterpreter throughout the executions.
 */
public class FilesManager{
    //CONSTANTS
    public static final String MASTER_OUTPUT_FOLDER = "src/rars/corrector/master_results/outputs/";
    public static final String MASTER_READABLE_FOLDER = "src/rars/corrector/master_results/inputs/readable/";
    public static final String MASTER_BINARY_FOLDER = "src/rars/corrector/master_results/inputs/binaries/";
    public static final FilenameFilter FILTER_INPUTS = (f, name) -> name.contains("inputs");
    public static final FilenameFilter FILTER_OUTPUTS = (f, name) -> name.contains("outputs");
    public static final String CORRECTION_FILE = "src/rars/corrector/Correction.txt";
    public static final String STUDENT_HEADER =
            "****************************************\n" +
            "Fichier : %s\n" +
            "****************************************\n";

    //FILES
    public final File MASTER_FILE;
    private File[] studentFiles;

    private static int topIndex = 0;

    /**
     * Builds the file manager from the command-line arguments. The first
     * element of the array designates the master file, and every following
     * element designates a student file to correct.
     *
     * @param filesName array of at least two elements:
     *                  filesName[0]: the path of the master file
     *                  filesName[1..n-1]}: the paths of the student files
     */
    public FilesManager(String [] filesName){
        MASTER_FILE = new File(filesName[0]);
        studentFiles = new File[filesName.length-1];

        prepareMasterFolders();

        for(int i = 1; i < filesName.length; ++i){
            studentFiles[i-1] = new File(filesName[i]);
        }
    }

    /**
     * Returns the number of student files to correct.
     *
     * @return the size of the student files array
     */
    public int getNumberOfFiles(){
        return studentFiles.length;
    }

    /**
     * Returns all the student files to correct.
     *
     * @return the array of student files, in the order supplied to the constructor
     */
    public File[] getStudentFiles(){
        return studentFiles;
    }

    /**
     * Returns the student file corresponding to the given index.
     *
     * @param index index of the student file, between {@code 0} and {@code getNumberOfFiles() - 1}
     * @return the corresponding student file
     */
    public File getStudentFile(int index){
        if(index < 0 || index >= studentFiles.length){
            return null;
        }
        return studentFiles[index];
    }

    /**
     * Returns the reference input files (generated by the master file), sorted
     * by name.
     *
     * @return the array of master input files
     */
    public File[] getReadableMasterInputsFiles() {
        return getFiles(MASTER_READABLE_FOLDER, FILTER_INPUTS);
    }

    /**
     * Returns the reference input files (generated by the master file), sorted
     * by name.
     *
     * @return the array of master input files
     */
    public File[] getBinaryMasterInputsFiles() {
        return getFiles(MASTER_BINARY_FOLDER, FILTER_INPUTS);
    }

    /**
     * Returns the reference output files (generated by the master file), sorted
     * by name.
     *
     * @return the array of master output files
     */
    public File[] getMasterOutputsFiles() {
        return getFiles(MASTER_OUTPUT_FOLDER, FILTER_OUTPUTS);
    }

    /**
     * Returns the input files generated by the most recent execution of
     * ConcolicInterpreter, sorted by name.
     *
     * @return the array of input files from the most recent execution
     */
    public File[] getBinaryExecInputFiles(){
        return getFiles(ConcolicInterpreter.INPUT_BINARY_FOLDER_NAME, FILTER_INPUTS);
    }

    public File[] getReadableExecInputFiles(){
        return getFiles(ConcolicInterpreter.INPUT_READABLE_FOLDER_NAME, FILTER_INPUTS);
    }

    /**
     * Returns the output files generated by the most recent execution of
     * ConcolicInterpreter, sorted by name.
     *
     * @return the array of output files from the most recent execution
     */
    public File[] getExecOutputFiles(){
        return getFiles(ConcolicInterpreter.OUTPUT_FOLDER_NAME, FILTER_OUTPUTS);
    }

    /**
     * Saves into MASTER_FOLDER every input/output pair produced by the
     * most recent execution of ConcolicInterpreter.
     */
    public void saveExecutionResults() {
        File[] readableInputs = getReadableExecInputFiles();
        File[] binaryInputs = getBinaryExecInputFiles();
        File[] outputs = getExecOutputFiles();

        for(int i = 0; i < readableInputs.length; ++i) {
            saveExecutionResults(readableInputs[i], binaryInputs[i], outputs[i]);
            ++topIndex;
        }
    }

    /**
     * Copies the content of an input/output pair into MASTER_FOLDER.
     *
     * @param readableInputFile readable input file to copy
     * @param binaryInputFile  binary input file to copy
     * @param outputFile corresponding output file to copy
     */
    private void saveExecutionResults(File readableInputFile, File binaryInputFile, File outputFile) {
        try {
            byte[] binaryInputContent = Files.readAllBytes(binaryInputFile.toPath());
            String readableInputContent = Files.readString(readableInputFile.toPath());
            String outputContent = Files.readString(outputFile.toPath());

            String paddedIndex = String.format("%05d", topIndex);

            Files.write(Paths.get(MASTER_BINARY_FOLDER,"binary_inputs" + paddedIndex), binaryInputContent);
            Files.writeString(Paths.get(MASTER_READABLE_FOLDER, "readable_inputs" + paddedIndex), readableInputContent);
            Files.writeString(Paths.get(MASTER_OUTPUT_FOLDER, "outputs" + paddedIndex), outputContent);
        } catch (IOException e) {
            System.out.println("Error while saving execution result : " + e.getMessage());
            System.exit(1);
        }
    }

    /**
     * Adds, at the end of CORRECTION_FILE, a header identifying the
     * student file whose results are about to follow.
     *
     * @param index index of the student file in studentFiles
     */
    public void printStudentHeader(int index){
        try {
            PrintWriter pw = new PrintWriter(new FileWriter(CORRECTION_FILE, true));
            pw.printf(STUDENT_HEADER, studentFiles[index].getName());
            pw.close();
        } catch (IOException e)  {
            System.out.println("Error while writing header: " + e.getMessage());
        } catch (ArrayIndexOutOfBoundsException e) {
            return;
        }
    }

    private void prepareMasterFolders(){
        File[] dir = {
                new File(MASTER_OUTPUT_FOLDER),
                new File(MASTER_BINARY_FOLDER),
                new File(MASTER_READABLE_FOLDER)
        };

        try {
            for(File f : dir){
                Files.createDirectories(f.toPath());
            }
            } catch (IOException e) {
                System.out.println("Error creating results folders: " + e.getMessage());
            }

        try {
            for (File d : dir) {
                for (File f : d.listFiles())
                    if (!f.isDirectory())
                        f.delete();
            }

            File c = new File(CORRECTION_FILE);
            c.delete();
        } catch (NullPointerException e) {
            System.out.println("Error while cleaning folders: " + e.getMessage());
        }
    }

    /**
     * Cleans up the working directories before starting a new correction:
     * deletes every file (excluding subdirectories) found in the output folder
     * and the input folder of ConcolicInterpreter, as well as in
     * MASTER_FOLDER, then deletes the existing CORRECTION_FILE.
     */
    private void cleanFolders() {

    }

    /**
     * Lists, filters, and sorts by name the files of a given folder.
     *
     * @param folder path of the folder to list
     * @param filter filter to apply to the file names
     * @return the array of matching files, sorted by name
     */
    private File[] getFiles(String folder, FilenameFilter filter) {
        try {
            File fileFolder = new File(folder);
            File[] files = fileFolder.listFiles(filter);
            Arrays.sort(files, Comparator.comparing(File::getName));
            return files;
        } catch (NullPointerException e) {
            return null;
        }
    }
}
